SELECT NUMERO_PEDIDO,
		SUM(PRECO) AS TOTAL_VENDAS,
		CASE 
			WHEN SUM(PRECO) >= 50
				THEN 'META ATINGIDA'
			WHEN SUM(PRECO) >= 20 AND SUM(PRECO) < 50
				THEN 'ACEITÁVEL'
			ELSE
				'NÃO ATINGIDA'
		END AS STATUS_VENDAS
	FROM TB_DETALHE_PEDIDO
GROUP BY NUMERO_PEDIDO