--- UNIQUE ---
ALTER TABLE TBL_CLIENTE
ADD CONSTRAINT UQ_TBL_CLIENTE_CPF_CNPJ UNIQUE(CPF_CNPJ);

--- CHECK ---
ALTER TABLE TBL_CONTA
ADD CONSTRAINT CK_TBL_CONTA_AGENCIA CHECK(AGENCIA > 10);

--- DEFAULT ---
ALTER TABLE TBL_ENDERECO
ADD CONSTRAINT DF_COMPLEMENTO DEFAULT('N/A') FOR COMPLEMENTO_END;

--- CREATE COM CONSTRAINT PRIMARY KEY
CREATE TABLE TB_CLIENTE
(
	ID_CLIENTE INT IDENTITY,
	CONSTRAINT PK_CLIENTE_IDCLIENTE PRIMARY KEY(ID_CLIENTE)
);

-- CREATE COM CONSTRAINT PRIMARY KEY E FOREIGN KEY
CREATE TABLE TB_ENDERECO
(
	ID_ENDERECO INT IDENTITY,
	LOGRADOURO VARCHAR(50),
	NUMERO VARCHAR(20),
	BAIRRO VARCHAR(35),
	CEP VARCHAR(15),
	ID_CLIENTE INT,
	CONSTRAINT PK_ENDERECO_ID_ENDERECO PRIMARY KEY(ID_ENDERECO),
	CONSTRAINT FK_ENDERECO_CLIENTE_IDCLIENTE FOREIGN KEY(ID_CLIENTE)
	REFERENCES TB_CLIENTE(ID_CLIENTE)
);

-- ADICIONANDO CONSTRAINT FK EM TABELAS EXISTENTES
ALTER TABLE TB_ENDERECO
ADD CONSTRAINT FK_ENDERECO_CLIENTE_IDCLIENTE FOREIGN KEY(ID_CLIENTE)
REFERENCES TB_CLIENTE(ID_CLIENTE)

-- REMOVENDO CONSTRAINT FK DE TABELAS EXISTENTES
ALTER TABLE TB_ENDERECO
DROP CONSTRAINT FK_ENDERECO_CLIENTE_IDCLIENTE

