-- CAST
-- CONVERT

SELECT CONVERT(VARCHAR, GETDATE(), 108)


SELECT CONVERT(DECIMAL(10, 2), '123123.1231313')


SELECT CONVERT(INT, '1231231231')

SELECT 
	CONCAT('PRODUTO ', P.DESCRICAO, ' TEM O PREÇO DE ', D.PRECO)
FROM TB_PRODUTO P
JOIN TB_DETALHE_PEDIDO D
ON P.ID_PRODUTO = D.ID_PRODUTO