USE EMPRESA_DB

SELECT C2.NOME_COMPLETO,
		C2.CARGO,
		C2.SOMATORIA_QUANTIDADE,
		C2.SOMATORIA_PRECO,
		C2.VALOR_TOTAL,
		CASE
			WHEN C2.VALOR_TOTAL >= 5000
				THEN 'BATEU A META'
			ELSE
				'NÃO BATEU A META'
		END AS STATUS
FROM
	(SELECT CLI.NOME_COMPLETO,
			CLI.CARGO,
			C1.ANO_MES,
			C1.SOMATORIA_QUANTIDADE,
			C1.SOMATORIA_PRECO,
			C1.VALOR_TOTAL
	FROM
	(SELECT 
		P.ID_CLIENTE,
		SUBSTRING(CONVERT(VARCHAR, P.DATA_PEDIDO, 120), 1, 7) ANO_MES,
		SUM(D.QUANTIDADE) SOMATORIA_QUANTIDADE,
		SUM(D.PRECO) SOMATORIA_PRECO,
		SUM(D.QUANTIDADE) * SUM(D.PRECO) VALOR_TOTAL
		FROM TB_DETALHE_PEDIDO D
	JOIN TB_PEDIDO P ON D.NUMERO_PEDIDO = P.NUMERO_PEDIDO
	GROUP BY P.ID_CLIENTE, SUBSTRING(CONVERT(VARCHAR, P.DATA_PEDIDO, 120), 1, 7)) AS C1
	JOIN TB_CLIENTE CLI ON C1.ID_CLIENTE = CLI.ID_CLIENTE) AS C2