SELECT C1.CATEGORIA,
		C1.ANO,
		CONVERT(DECIMAL(15,2), C1.FATURAMENTO) AS FATURAMENTO,
		(C1.FATURAMENTO/C2.FATURAMENTO) * 100 [PERCENTUAL (%)]
FROM
	(SELECT CA.DESCRICAO CATEGORIA,
			YEAR(PE.DATA_PEDIDO) AS ANO,
			SUM(DE.QUANTIDADE * DE.PRECO) AS FATURAMENTO

		FROM TB_DETALHE_PEDIDO DE
		JOIN TB_PRODUTO PR
			ON DE.ID_PRODUTO = PR.ID_PRODUTO
		JOIN TB_CATEGORIA CA
			ON CA.ID_CATEGORIA = PR.ID_CATEGORIA
		JOIN TB_PEDIDO PE
			ON PE.NUMERO_PEDIDO = DE.NUMERO_PEDIDO
		WHERE YEAR(PE.DATA_PEDIDO) = 1996
		GROUP BY CA.DESCRICAO, YEAR(PE.DATA_PEDIDO)) AS C1
	INNER JOIN
	(SELECT 
			YEAR(PE.DATA_PEDIDO) AS ANO,
			SUM(DE.QUANTIDADE * DE.PRECO) AS FATURAMENTO

		FROM TB_DETALHE_PEDIDO DE
		JOIN TB_PRODUTO PR
			ON DE.ID_PRODUTO = PR.ID_PRODUTO
		JOIN TB_CATEGORIA CA
			ON CA.ID_CATEGORIA = PR.ID_CATEGORIA
		JOIN TB_PEDIDO PE
			ON PE.NUMERO_PEDIDO = DE.NUMERO_PEDIDO
		WHERE YEAR(PE.DATA_PEDIDO) = 1996
		GROUP BY YEAR(PE.DATA_PEDIDO)) AS C2
	ON C1.ANO = C2.ANO