-- VENDEDOR QUE TEVE O MAIOR VALOR NO TOTAL DE SUAS VENDAS
SELECT C1.NOME_COMPLETO, C1.TOTAL FROM 
(
	SELECT TOP 1 C2.NOME_COMPLETO, SUM(D.PRECO) TOTAL FROM TB_DETALHE_PEDIDO D
	JOIN (SELECT PE.NUMERO_PEDIDO, F.NOME_COMPLETO FROM TB_PEDIDO PE
			JOIN TB_FUNCIONARIO F ON PE.ID_FUNCIONARIO = F.ID_FUNCIONARIO
			WHERE F.CARGO = 'Representante de Vendas') AS C2
			ON C2.NUMERO_PEDIDO = D.NUMERO_PEDIDO
			GROUP BY C2.NOME_COMPLETO 
			ORDER BY TOTAL DESC
) AS C1