-- QUAL PRODUTO TEVE MAIOR QUANTIDADE DE VENDAS NO MÊS 7 DE 1996
SELECT TOP 1 P.DESCRICAO, SUM(D.QUANTIDADE) TOTAL FROM TB_PRODUTO P
JOIN TB_DETALHE_PEDIDO D ON P.ID_PRODUTO = D.ID_PRODUTO
JOIN TB_PEDIDO PE ON D.NUMERO_PEDIDO = PE.NUMERO_PEDIDO
WHERE PE.DATA_PEDIDO BETWEEN '1996-07-01' AND  '1996-07-31'
GROUP BY P.DESCRICAO
ORDER BY SUM(D.QUANTIDADE) DESC

-- QUAL CLIENTE TEVE O MAIOR GASTO NO MÊS 7 DE 1996
SELECT TOP 1 C.NOME_COMPLETO, SUM(DP.PRECO) TOTAL FROM TB_CLIENTE C
JOIN TB_PEDIDO P ON C.ID_CLIENTE = P.ID_CLIENTE
JOIN TB_DETALHE_PEDIDO DP ON DP.NUMERO_PEDIDO = P.NUMERO_PEDIDO
WHERE P.DATA_PEDIDO BETWEEN '1996-07-01' AND '1996-07-31'
GROUP BY C.NOME_COMPLETO
ORDER BY SUM(DP.PRECO) DESC