-- LISTA DE TODOS OS CLIENTES QUE MORAM NA ALEMANHA
SELECT * FROM TB_CLIENTE C
JOIN TB_ENDERECO E ON C.ID_CLIENTE = E.ID_CLIENTE
WHERE E.PAIS = 'Alemanha'

SELECT * FROM TB_CATEGORIA

-- LISTA DE TODOS OS CLIENTES QUE COMPRARAM PRODUTOS DA CATEGORIA BEBIDA
SELECT C.NOME_COMPLETO, CA.DESCRICAO FROM TB_CLIENTE C
JOIN TB_PEDIDO PE ON C.ID_CLIENTE = PE.ID_CLIENTE
JOIN TB_DETALHE_PEDIDO DE ON DE.NUMERO_PEDIDO = PE.NUMERO_PEDIDO
JOIN TB_PRODUTO PR ON PR.ID_PRODUTO = DE.ID_PRODUTO
JOIN TB_CATEGORIA CA ON CA.ID_CATEGORIA = PR.ID_CATEGORIA
WHERE CA.DESCRICAO = 'Bebidas'