SELECT * FROM TB_FUNCIONARIO

SELECT DISTINCT F.CARGO FROM TB_FUNCIONARIO F

SELECT AVG(F.SALARIO) MEDIA_COOR_RH FROM TB_FUNCIONARIO F
WHERE F.CARGO = 'Coordenador de RH' 

SELECT AVG(F.SALARIO) MEDIA_COOR_VENDAS FROM TB_FUNCIONARIO F
WHERE F.CARGO = 'Coordenador de Vendas Internas' 

SELECT AVG(F.SALARIO) MEDIA_GERENTE FROM TB_FUNCIONARIO F
WHERE F.CARGO = 'Gerente de Vendas' 

SELECT AVG(F.SALARIO) MEDIA_REPRESENTANTE FROM TB_FUNCIONARIO F
WHERE F.CARGO = 'Representante de Vendas' 

SELECT AVG(F.SALARIO) MEDIA_VICE FROM TB_FUNCIONARIO F
WHERE F.CARGO = 'Vice-Presidente de Vendas'

-- QUAIS CARGOS POSSUEM A MÉDIA SALARIAL MAIOR QUE A MÉDIA SALARIAL DO CARGO DE COORDENADOR DE VENDAS INTERNAS
SELECT F.CARGO, AVG(F.SALARIO) FROM TB_FUNCIONARIO F
GROUP BY F.CARGO
HAVING AVG(F.SALARIO) > (SELECT AVG(F.SALARIO) FROM TB_FUNCIONARIO F
						WHERE F.CARGO = 'Coordenador de Vendas Internas')

-- QUAL PRODUTO TEVE MAIS VENDAS EM 07 DE 1996
SELECT 
	C1.DESCRICAO, 
	C1.QUANTIDADE 
	FROM 
	(
		SELECT TOP 1 PR.DESCRICAO, SUM(D.QUANTIDADE) QUANTIDADE FROM TB_PRODUTO PR
			JOIN TB_DETALHE_PEDIDO D ON PR.ID_PRODUTO = D.ID_PRODUTO
		WHERE D.NUMERO_PEDIDO IN 
			(
				SELECT PE.NUMERO_PEDIDO FROM TB_PEDIDO PE
				WHERE PE.DATA_PEDIDO BETWEEN '1996-07-01' AND '1996-07-31')
				GROUP BY PR.DESCRICAO
				ORDER BY SUM(D.QUANTIDADE) DESC
			) AS C1