PRINT CONCAT(' A', ' B', 'C', 'D')

PRINT CONCAT('TESTE', '  TESTE')
PRINT CONCAT('TESTE', LTRIM('  TESTE'))

PRINT ('   TESTE   ')
PRINT TRIM('   TESTE   ')

PRINT LEFT('TESTE', 3)

PRINT SUBSTRING('TESTE', 1, 3)
PRINT LEN('TESTE')
PRINT UPPER('teste')
PRINT LOWER('TESTE')

PRINT 0000000.44

PRINT REPLICATE('Q', 40)

PRINT CONCAT(REPLICATE('0', 6), 0.44)

PRINT REPLACE('TESTE', 'T', 'M')

PRINT REVERSE('TESTE')
