SELECT NUMERO_PEDIDO, SUM(PRECO) AS MEDIA FROM TB_DETALHE_PEDIDO
GROUP BY NUMERO_PEDIDO

SELECT NUMERO_PEDIDO, COUNT(*) FROM TB_DETALHE_PEDIDO
GROUP BY NUMERO_PEDIDO

-- SUM(X), MAX(X), MIN(X), AVG(X), COUNT(X)