SELECT * FROM TB_DETALHE_PEDIDO

SELECT NUMERO_PEDIDO, COUNT(*) FROM TB_DETALHE_PEDIDO
WHERE NUMERO_PEDIDO IN (10249, 10250, 10251, 10256)
GROUP BY NUMERO_PEDIDO
HAVING COUNT(*) = 3

SELECT * FROM TB_CLIENTE

INSERT INTO TB_CLIENTE
VALUES
('OPOPO', 'MARCOS ALBERTO', 'MARIA JOAQUINA', 'VENDEDOR')

SELECT NOME_COMPLETO, COUNT(NOME_COMPLETO) FROM TB_CLIENTE
GROUP BY NOME_COMPLETO
HAVING COUNT(NOME_COMPLETO) > 1

SELECT * FROM TB_CLIENTE
WHERE NOME_COMPLETO = 'MARCOS ALBERTO'

DELETE FROM TB_CLIENTE WHERE ID_CLIENTE = 'OPOPO'