SELECT * FROM TB_ENDERECO
WHERE PAIS IN ('EUA','SUÉCIA','FRANÇA')

SELECT * FROM TB_ENDERECO
WHERE PAIS NOT IN ('EUA','SUÉCIA','FRANÇA')

SELECT * FROM TB_ENDERECO
WHERE REGIAO IS NULL

SELECT * FROM TB_ENDERECO
WHERE REGIAO IS NOT NULL

SELECT LOGRADOURO, CIDADE, PAIS, ISNULL(REGIAO, 'N/C') FROM TB_ENDERECO