SELECT PAIS FROM TB_ENDERECO
WHERE ID_CLIENTE IS NOT NULL
--INTERSECT -- VÊ OS ITENS QUE ESTÃO NAS DUAS QUERYS
EXCEPT -- VÊ TUDO QUE VEM DO LADO ESQUERDO MAS NÃO NO DIREITO 
SELECT PAIS FROM TB_ENDERECO
WHERE ID_FUNCIONARIO IS NOT NULL