SELECT DISTINCT	
		C.ID_CLIENTE,
		C.NOME_COMPLETO,
		C.CARGO,
		C.CONTATO,
		E.LOGRADOURO, 
		E.CIDADE, 
		E.PAIS
FROM 
TB_ENDERECO AS E LEFT JOIN TB_CLIENTE AS C 
ON C.ID_CLIENTE = E.ID_CLIENTE

SELECT DISTINCT	
		C.ID_CLIENTE,
		C.NOME_COMPLETO,
		C.CARGO,
		C.CONTATO,
		E.LOGRADOURO, 
		E.CIDADE, 
		E.PAIS
FROM 
TB_ENDERECO AS E RIGHT JOIN TB_CLIENTE AS C 
ON C.ID_CLIENTE = E.ID_CLIENTE

SELECT * FROM TB_CLIENTE

INSERT INTO TB_CLIENTE
(ID_CLIENTE, NOME_COMPLETO, CONTATO, CARGO)
VALUES
('AAAAA', 'MARCOS ALBERTO', 'MARIA JOAQUINA', 'VENDEDOR'),
('BBBBB', 'MONICA SANTOS', 'JOSE SILVA', 'ATENDENTE DE MARKETING'),
('CCCCC', 'JOANA ALVES', 'ANA SILVA', 'PROPRIETARIA')