USE EMPRESA_DB

SELECT * FROM TB_CLIENTE
WHERE CARGO LIKE 'REPRESENTANTE%' -- Começa com representante

SELECT * FROM TB_CLIENTE
WHERE CARGO LIKE '%PEDIDOS' -- Termina com pedidos

SELECT * FROM TB_CLIENTE
WHERE CARGO LIKE '% DE %'