CREATE TABLE TB_CLIENTE
(
	ID_CLIENTE INT IDENTITY,
	NOME VARCHAR(70),
	CPF VARCHAR(11),
	DATA_NASCIMENTO DATETIME2,
	EMAIL VARCHAR(70),
	CONSTRAINT PK_CLIENTE PRIMARY KEY(ID_CLIENTE)
)

SELECT * FROM TB_CLIENTE;

INSERT INTO TB_CLIENTE
(NOME, CPF, DATA_NASCIMENTO, EMAIL)
VALUES
('Ítalo', '23088746863', '1997-09-17', 'italo@email.com');