CREATE TABLE DBO.TESTE_INDEX
(
	CPF VARCHAR(11) NOT NULL,
	NOME VARCHAR(50) NULL,
	RG VARCHAR(10) NULL
)

CREATE UNIQUE CLUSTERED INDEX IX_CPF
ON DBO.TESTE_INDEX (CPF)

CREATE NONCLUSTERED INDEX IX_RG_NOME
ON DBO.TESTE_INDEX (RG, NOME)

DROP INDEX DBO.TESTE_INDEX.IX_RG

EXEC sp_helpindex TESTE_INDEX