SELECT * FROM TB_FUNCIONARIO
WHERE SALARIO = 5000 -- IGUAL

SELECT * FROM TB_FUNCIONARIO
WHERE SALARIO <> 5000 -- DIFERENTE

SELECT * FROM TB_FUNCIONARIO
WHERE SALARIO < 5000 -- MENOR

SELECT * FROM TB_FUNCIONARIO
WHERE SALARIO <= 5000 -- MENOR IGUAL

SELECT * FROM TB_FUNCIONARIO
WHERE SALARIO >= 5000 AND SALARIO <= 9500

SELECT * FROM TB_FUNCIONARIO
WHERE SALARIO BETWEEN 5000 AND 9500