USE TESTE

SELECT * FROM TBL_CLIENTE
ORDER BY CPF_CNPJ ASC

SELECT * FROM TBL_CLIENTE
ORDER BY CPF_CNPJ DESC

SELECT TOP 1 WITH TIES * FROM TBL_CLIENTE
ORDER BY DATA_NASCIMENTO -- WITH TIES TRAZ OS REPETIDOS