-- TOTAL VENDIDO EM CADA UM DOS MESES FILTRADO POR UM DETERMINADO ANO
CREATE PROCEDURE STP_TOTAL_VENDIDO @ANO AS INT
AS BEGIN
	SELECT 
		MONTH(P.DATA_PEDIDO) AS MES,
		YEAR(P.DATA_PEDIDO) AS ANO,
		SUM(D.PRECO) AS TOTAL_VENDIDO
	FROM 
		TB_PEDIDO P
		JOIN 
		TB_DETALHE_PEDIDO D
		ON P.NUMERO_PEDIDO = D.NUMERO_PEDIDO
	WHERE 
		YEAR(P.DATA_PEDIDO) = @ANO
	GROUP BY 
		MONTH(P.DATA_PEDIDO), YEAR(P.DATA_PEDIDO)
	ORDER BY 1
END

EXEC STP_TOTAL_VENDIDO 1997