-- ITENS DO PEDIDO E DETALHES PEDIDO POR PERÍODO DE DATA E CLIENTE E/OU FUNCIONÁRIO
CREATE PROC STP_ITENS_PEDIDO @DT1 DATETIME2, @DT2 DATETIME2, @CLIENTE VARCHAR(50) = '%', @FUNCIONARIO VARCHAR(50) = '%'
AS BEGIN
	SELECT
		P.NUMERO_PEDIDO,
		P.DATA_PEDIDO,
		D.PRECO,
		D.DESCONTO,
		P.FRETE,
		C.NOME_COMPLETO CLIENTE,
		F.NOME_COMPLETO FUNCIONARIO
	FROM
		TB_PEDIDO P
		JOIN
		TB_DETALHE_PEDIDO D
		ON P.NUMERO_PEDIDO = D.NUMERO_PEDIDO
		JOIN
		TB_CLIENTE C
		ON P.ID_CLIENTE = C.ID_CLIENTE
		JOIN 
		TB_FUNCIONARIO F
		ON F.ID_FUNCIONARIO = P.ID_FUNCIONARIO
	WHERE 
		P.DATA_PEDIDO BETWEEN @DT1 AND @DT2 AND C.NOME_COMPLETO LIKE @CLIENTE AND F.NOME_COMPLETO LIKE @FUNCIONARIO
END

EXEC STP_ITENS_PEDIDO @DT1='1996-01-01', @DT2='1996-12-31'