CREATE PROCEDURE BUSCAR_ENDERECO_POR_ENTIDADE @ENTIDADE AS VARCHAR(30)
AS 
BEGIN
	IF @ENTIDADE = 'CLIENTE'
		SELECT * FROM TB_ENDERECO WHERE ID_CLIENTE IS NOT NULL
	ELSE IF @ENTIDADE = 'FUNCIONARIO'
		SELECT * FROM TB_ENDERECO WHERE ID_FUNCIONARIO IS NOT NULL
	ELSE IF @ENTIDADE = 'FORNECEDOR'
		SELECT * FROM TB_ENDERECO WHERE ID_FORNECEDOR IS NOT NULL
	ELSE
		SELECT 'OPÇÃO INVÁLIDA, SELECIONE ALGUMAS DESSAS OPÇÕES: CLIENTE, FUNCIONÁRIO OU FORNECEDOR'
END

ALTER PROCEDURE BUSCAR_ENDERECO_POR_ENTIDADE @ENTIDADE AS VARCHAR(30)
AS 
BEGIN
	IF @ENTIDADE = 'CLIENTE'
		SELECT LOGRADOURO, CIDADE, CEP, PAIS FROM TB_ENDERECO WHERE ID_CLIENTE IS NOT NULL
	ELSE IF @ENTIDADE = 'FUNCIONARIO'
		SELECT LOGRADOURO, CIDADE, CEP, PAIS FROM TB_ENDERECO WHERE ID_FUNCIONARIO IS NOT NULL
	ELSE IF @ENTIDADE = 'FORNECEDOR'
		SELECT LOGRADOURO, CIDADE, CEP, PAIS FROM TB_ENDERECO WHERE ID_FORNECEDOR IS NOT NULL
	ELSE
		SELECT 'OPÇÃO INVÁLIDA, SELECIONE ALGUMAS DESSAS OPÇÕES: CLIENTE, FUNCIONÁRIO OU FORNECEDOR'
END

EXEC BUSCAR_ENDERECO_POR_ENTIDADE @ENTIDADE = 'FORNECEDOR'

CREATE PROCEDURE CALCULAR_IDADE @IDADE AS INT OUTPUT, @DATA_NASCIMENTO AS DATETIME2
AS 
BEGIN
	SET @IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE())
END

DECLARE @IDADE_OUT AS INT = 0;

PRINT 'IDADE ANTES: ' + CAST(@IDADE_OUT AS VARCHAR(2))

EXEC CALCULAR_IDADE @IDADE_OUT OUTPUT, @DATA_NASCIMENTO = '1988-06-06'

PRINT 'IDADE DEPOIS: ' + CAST(@IDADE_OUT AS VARCHAR(2))