-- TRAGA A DESCRIÇÃO DOS PRODUTOS QUE POSSUEM O PREÇO MAIOR QUE A MÉDIA DE TODOS OS PRODUTOS
SELECT P.DESCRICAO FROM TB_PRODUTO P
WHERE P.PRECO > (SELECT AVG(P2.PRECO) FROM TB_PRODUTO P2)

-- TRAGA TODOS OS CLIENTES QUE EXISTA PEDIDOS NO MÊS 7 DE 1996
SELECT C.* FROM TB_CLIENTE C
WHERE EXISTS (SELECT * FROM TB_PEDIDO P
				WHERE C.ID_CLIENTE = P.ID_CLIENTE
				AND P.DATA_PEDIDO BETWEEN '1996-07-01' AND '1996-07-31')
				AND C.ID_CLIENTE = 'CHOPS'

-- TRAGA O NOME E TOTAL DE PEDIDOS DE CADA CLIENTE
SELECT C.NOME_COMPLETO,
		(SELECT COUNT(*) FROM TB_PEDIDO P WHERE P.ID_CLIENTE = C.ID_CLIENTE) [TOTAL PEDIDOS]
FROM TB_CLIENTE C
ORDER BY [TOTAL PEDIDOS]