UPDATE TB_PRODUTO
SET PRECO -= 1
WHERE ID_CATEGORIA = (SELECT ID_CATEGORIA FROM TB_CATEGORIA
						WHERE DESCRICAO = 'Bebidas')

SELECT PRECO FROM TB_PRODUTO
WHERE ID_CATEGORIA = (SELECT ID_CATEGORIA FROM TB_CATEGORIA
						WHERE DESCRICAO = 'Bebidas')

DELETE FROM TB_PEDIDO
WHERE ID_FUNCIONARIO = (SELECT ID_FUNCIONARIO FROM TB_FUNCIONARIO
						WHERE CARGO = 'Vice-Presidente de Vendas')