CREATE TABLE TBL_CLIENTE (
	ID_CLIENTE INT PRIMARY KEY NOT NULL IDENTITY,
	NOME VARCHAR(80) NOT NULL,
	CPF_CNPJ VARCHAR(11) NOT NULL,
	CPF_CNPJ_FILIAL VARCHAR(4) NOT NULL,
	CPF_CNPJ_CONTROLE VARCHAR(2) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
);

CREATE TABLE TBL_CONTA (
	ID_CONTA INT PRIMARY KEY NOT NULL IDENTITY,
	AGENCIA INT NOT NULL,
	DIG_AGENCIA INT NOT NULL,
	CONTA INT NOT NULL,
	DIG_CONTA INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	FOREIGN KEY (ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE),
);

CREATE TABLE TBL_ENDERECO (
	ID_ENDERECO INT PRIMARY KEY NOT NULL IDENTITY,
	NOME_BAIRRO VARCHAR(50) NOT NULL,
	NOME_CIDADE VARCHAR(50) NOT NULL,
	NOME_ESTADO VARCHAR(50) NOT NULL,
	NOME_PAIS VARCHAR(50) NOT NULL,
	LOGRADOURO VARCHAR(100) NOT NULL,
	N_CASA INT NOT NULL,
	COMPLEMENTO_END VARCHAR(50) NULL,
	CEP VARCHAR(8) NOT NULL,
	ID_CLIENTE INT NOT NULL,
	FOREIGN KEY (ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE)
);

CREATE TABLE TBL_TELEFONE (
	ID_TELEFONE INT PRIMARY KEY NOT NULL IDENTITY,
	DDI INT NOT NULL,
	DDD INT NOT NULL,
	N_TELEFONE INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	FOREIGN KEY (ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE)
);

/* 1-SELECT FROM de todas as tabelas*/
SELECT * FROM TBL_CLIENTE;
SELECT * FROM TBL_CONTA;
SELECT * FROM TBL_ENDERECO;
SELECT * FROM TBL_TELEFONE;

SELECT * FROM TBL_CLIENTE INNER JOIN TBL_CONTA ON TBL_CLIENTE.ID_CLIENTE = TBL_CONTA.ID_CLIENTE;
SELECT * FROM TBL_CLIENTE INNER JOIN TBL_ENDERECO ON TBL_CLIENTE.ID_CLIENTE = TBL_ENDERECO.ID_CLIENTE;
SELECT * FROM TBL_CLIENTE INNER JOIN TBL_TELEFONE ON TBL_CLIENTE.ID_CLIENTE = TBL_TELEFONE.ID_CLIENTE;

INSERT INTO TBL_CLIENTE (NOME, CPF_CNPJ, CPF_CNPJ_FILIAL, CPF_CNPJ_CONTROLE, DATA_NASCIMENTO)
VALUES ('Ítalo Paiva Penha', 23088746863, 0000, 00, '1997-09-17');
INSERT INTO TBL_CONTA (AGENCIA, DIG_AGENCIA, CONTA, DIG_CONTA, ID_CLIENTE)
VALUES (2216, 0, 55685, 8, 1);
INSERT INTO TBL_ENDERECO (NOME_BAIRRO, NOME_CIDADE, NOME_ESTADO, NOME_PAIS, LOGRADOURO, N_CASA, CEP, ID_CLIENTE)
VALUES ('Perus', 'São Paulo', 'São Paulo', 'Brasil', 'Rua Visconti Coaracy', 343, '05205280', 1);
INSERT INTO TBL_TELEFONE (DDI, DDD, N_TELEFONE, ID_CLIENTE)
VALUES (55, 11, 983901193, 1);

SELECT * FROM TBL_CLIENTE 
INNER JOIN TBL_CONTA ON TBL_CLIENTE.ID_CLIENTE = TBL_CONTA.ID_CLIENTE
INNER JOIN TBL_ENDERECO ON TBL_CLIENTE.ID_CLIENTE = TBL_ENDERECO.ID_CLIENTE
INNER JOIN TBL_TELEFONE ON TBL_CLIENTE.ID_CLIENTE = TBL_ENDERECO.ID_CLIENTE;

UPDATE TBL_CLIENTE SET NOME = 'Ítalo' WHERE ID_CLIENTE = 1;
UPDATE TBL_CONTA SET AGENCIA = 2251 WHERE ID_CLIENTE = 1;
UPDATE TBL_ENDERECO SET N_CASA = 647437 WHERE ID_CLIENTE = 1;
UPDATE TBL_TELEFONE SET DDD = 12 WHERE ID_CLIENTE = 1;

UPDATE TBL_CONTA SET CONTA = 66438 WHERE ID_CONTA = 2;

DELETE FROM TBL_CLIENTE WHERE ID_CLIENTE = 1; /* ERRO, PENSAR NO Q FAZER*/

DELETE FROM TBL_CONTA WHERE ID_CONTA = 2;

DELETE FROM TBL_CONTA WHERE ID_CLIENTE = 1;


