USE EMPRESA_DB

SELECT NOME_COMPLETO, CONTATO, CARGO FROM TB_CLIENTE
UNION
SELECT EMPRESA, CONTATO, CARGO FROM TB_FORNECEDOR

SELECT PAIS, 'CLIENTE' FROM TB_ENDERECO
WHERE ID_CLIENTE IS NOT NULL
UNION ALL -- TRAZ ATÉ OS REPETIDOS
SELECT PAIS, 'FORNECEDOR' FROM TB_ENDERECO
WHERE ID_FORNECEDOR IS NOT NULL