UPDATE TB_PRODUTO
SET PRECO -= 1
FROM TB_PRODUTO P 
JOIN TB_CATEGORIA C
ON P.ID_CATEGORIA = C.ID_CATEGORIA	
WHERE C.DESCRICAO = 'Condimentos'

SELECT P.PRECO FROM TB_PRODUTO P 
JOIN TB_CATEGORIA C
ON P.ID_CATEGORIA = C.ID_CATEGORIA	
WHERE C.DESCRICAO = 'Condimentos'

DELETE TB_PEDIDO 
FROM TB_PEDIDO P
JOIN TB_FUNCIONARIO F
ON P.ID_FUNCIONARIO = F.ID_FUNCIONARIO
WHERE F.CARGO = 'Vice-Presidente de Vendas'

SELECT * FROM TB_PEDIDO P
JOIN TB_FUNCIONARIO F
ON P.ID_FUNCIONARIO = F.ID_FUNCIONARIO
WHERE F.CARGO = 'Vice-Presidente de Vendas'

