CREATE DATABASE db_marketplace

USE db_marketplace

CREATE TABLE Usuarios(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	CPF BIGINT NOT NULL,
	Senha VARCHAR(50) NOT NULL,
	Endereco VARCHAR(100) NOT NULL,
)

CREATE TABLE Categorias(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Descrcicao VARCHAR(50) NULL,
)

CREATE TABLE Produtos(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Descricao VARCHAR(150) NOT NULL,
	Preco FLOAT NOT NULL,
	FK_Criador INT NOT NULL,
	FK_Categoria INT NOT NULL,
	FOREIGN KEY (FK_Criador) REFERENCES Usuarios (Id),
	FOREIGN KEY (FK_Categoria) REFERENCES Categorias (Id)
)

DROP TABLE Usuarios
DROP TABLE Categorias
DROP TABLE Produtos