-- DDL
-- CREATE
-- ALTER
-- DROP

CREATE DATABASE db_classificados

USE db_classificados

CREATE TABLE Anunciantes(
	Id INT PRIMARY KEY NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Senha VARCHAR(100) NOT NULL,
	Endereco VARCHAR(100) NOT NULL
	)

CREATE TABLE Classificados(
	Produto VARCHAR(50) NOT NULL,
	Descricao VARCHAR(100) NOT NULL,
	FK_Criador INT NOT NULL,
	FOREIGN KEY (FK_Criador) REFERENCES Anunciantes (Id)
	)